site: SeGoosheh

url: https://index.jekyllthemes.io
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  commercial-buildings:
    output: true
    permalink: /projects/commercial-building/:slug
  concept-designs:
    output: true
    permalink: /projects/concept-design/:slug
  hotels:
    output: true
    permalink: /projects/hotel/:slug
  industrial-buildings:
    output: true
    permalink: /projects/industrial-building/:slug
  interior-designs:
    output: true
    permalink: /projects/interior-design/:slug
  office-buildings:
    output: true
    permalink: /projects/office-building/:slug
  residential-buildings:
    output: true
    permalink: /projects/residential-building/:slug
  villas:
    output: true
    permalink: /projects/villa/:slug
  graphic-designs:
    output: true
    permalink: /projects/graphic-design/:slug
  product-designs:
    output: true
    permalink: /projects/product-design/:slug
  competitions:
    output: true
    permalink: /projects/competition/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "/projects/"
      type: "commercial-buildings"
    values:
      layout: "commercial-building"
  -
    scope:
      path: "/projects/"
      type: "concept-designs"
    values:
      layout: "concept-design"
  -
    scope:
      path: "/projects/"
      type: "hotels"
    values:
      layout: "hotel"
  -
    scope:
      path: "/projects/"
      type: "industrial-buildings"
    values:
      layout: "industrial-building"
  -
    scope:
      path: "/projects/"
      type: "interior-designs"
    values:
      layout: "interior-design"
  -
    scope:
      path: "/projects/"
      type: "Office Buildings"
    values:
      layout: "office-building"
  -
    scope:
      path: "/projects/"
      type: "Residential Buildings"
    values:
      layout: "residential-building"
  -
    scope:
      path: "/projects/"
      type: "Villas"
    values:
      layout: "villa"
  -
    scope:
      path: "/projects/"
      type: "Graphic Designs"
    values:
      layout: "graphic-design"
  -
    scope:
      path: "/projects/"
      type: "Product Designs"
    values:
      layout: "product-design"
  - scope:
      path: "/projects/"
      type: "Competitions"
    values:
      layout: "competition"


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"

title: "segoosheh"
description: "architecture and design studio"
url: "https://www.segoosheh.com"
author: fariba firooz
  