site: Index Jekyll Theme

url: https://index.jekyllthemes.io
baseurl: segoosheh

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  commercial-buildings:
    output: true
    permalink: /projects/commercial-building/:slug
  concept-designs:
    output: true
    permalink: /projects/concept-design/:slug
  hotels:
    output: true
    permalink: /projects/hotel/:slug
  industrial-buildings:
    output: true
    permalink: /projects/industrial-building/:slug
  interior-designs:
    output: true
    permalink: /projects/interior-design/:slug
  office-buildings:
    output: true
    permalink: /projects/office-building/:slug
  residential-buildings:
    output: true
    permalink: /projects/residential-building/:slug
  villas:
    output: true
    permalink: /projects/villa/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "/projects/"
      type: "commercial-buildings"
    values:
      layout: "commercial-building"
  -
    scope:
      path: "/projects/"
      type: "concept-designs"
    values:
      layout: "concept-design"
  -
    scope:
      path: "/projects/"
      type: "hotels"
    values:
      layout: "hotel"
  -
    scope:
      path: "/projects/"
      type: "industrial-buildings"
    values:
      layout: "industrial-building"
  -
    scope:
      path: "/projects/"
      type: "interior-designs"
    values:
      layout: "interior-design"
  -
    scope:
      path: "/projects/"
      type: "Office Buildings"
    values:
      layout: "office-building"
  -
    scope:
      path: "/projects/"
      type: "Residential Buildings"
    values:
      layout: "residential-building"
  -
    scope:
      path: "/projects/"
      type: "Villas"
    values:
      layout: "villa"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  